SOLIDplate.Application.Services.SignalR.Hubs Latest version: 1.0.0.1
SOLIDplate.Application.Services.SignalR.Hubs.Interfaces Latest version: 1.0.0.1
SOLIDplate.Application.Services.Clients.SignalR Latest version: 1.0.0.1
SOLIDplate.Application.Services.Clients.SignalR.Interfaces Latest version: 1.0.0.1
SOLIDplate.Application.Services.Clients.Wcf Latest version: 1.0.0.1
SOLIDplate.Application.Services.SignalR Latest version: 1.0.0.1
SOLIDplate.Application.Services.WebApi Latest version: 1.0.0.1
SOLIDplate.Application.Unity Latest version: 1.0.0.1
SOLIDplate.Application.Unity.SignalR Latest version: 1.0.0.1
SOLIDplate.Common Latest version: 1.0.0.1
SOLIDplate.Common.Portable Latest version: 1.0.0.1
SOLIDplate.Domain.Command.Services.EntityFramework Latest version: 1.0.0.1
SOLIDplate.Domain.Command.Services.Interfaces Latest version: 1.0.0.1
SOLIDplate.Domain.Entities Latest version: 1.0.0.1
SOLIDplate.Domain.Entities.Interfaces Latest version: 1.0.0.1
SOLIDplate.Domain.Integration.Services.Interfaces Latest version: 1.0.0.1
SOLIDplate.Domain.Query.Services Latest version: 1.0.0.1
SOLIDplate.Domain.Query.Services.EntityFramework Latest version: 1.0.0.1
SOLIDplate.Domain.Query.Services.Interfaces Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Data.EntityFramework.Configurations Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Data.EntityFramework.Interfaces Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Data.Interfaces Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Data.Services.EntityFramework Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Data.Services.EntityFramework.Interfaces Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Repository Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Repository.EntityFramework Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Repository.EntityFramework.Interfaces Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Repository.Interfaces Latest version: 1.0.0.1
SOLIDplate.Application.Services.Clients.Wcf.Interfaces Latest version: 1.0.0.1
SOLIDplate.Application.Services.Clients.WebApi Latest version: 1.0.0.1
SOLIDplate.Application.Services.Clients.WebApi.Interfaces Latest version: 1.0.0.1
SOLIDplate.Application.Unity.WebApi Latest version: 1.0.0.1
SOLIDplate.Domain.Command.Services Latest version: 1.0.0.1
SOLIDplate.Infrastructure.Data.EntityFramework Latest version: 1.0.0.1
SOLIDplate.Json.Net Latest version: 1.0.0.1
SOLIDplate.Domain.Integration.Services Latest version: 1.0.0.1
SOLIDplate.Presentation.ViewModels Latest version: 1.0.0.1
SOLIDplate.Presentation.ViewModels.Interfaces Latest version: 1.0.0.1
SOLIDplate.Presentation.Views.Xamarin Latest version: 1.0.0.1